name: Android Debug Build and Upload

on:
  push:
    branches: [ main ] # Triggers the workflow on pushes to the 'main' branch

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java Development Kit
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download and Extract Gradle Wrapper JAR
        run: |
          GRADLE_DIST_URL="https://services.gradle.org/distributions/gradle-9.0.0-bin.zip"
          GRADLE_VERSION="9.0.0"
          WRAPPER_DIR="gradle/wrapper"
          TEMP_UNZIP_DIR="gradle_dist_temp"
          
          mkdir -p "$WRAPPER_DIR"
          mkdir -p "$TEMP_UNZIP_DIR"
          
          curl -L "$GRADLE_DIST_URL" -o gradle-distribution.zip
          unzip gradle-distribution.zip -d "$TEMP_UNZIP_DIR"
          
          # Try common locations for gradle-wrapper.jar within the unzipped distribution
          if [ -f "${TEMP_UNZIP_DIR}/gradle-${GRADLE_VERSION}/lib/gradle-wrapper.jar" ]; then
            cp "${TEMP_UNZIP_DIR}/gradle-${GRADLE_VERSION}/lib/gradle-wrapper.jar" "$WRAPPER_DIR/gradle-wrapper.jar"
          elif [ -f "${TEMP_UNZIP_DIR}/gradle-${GRADLE_VERSION}/gradle/wrapper/gradle-wrapper.jar" ]; then
            cp "${TEMP_UNZIP_DIR}/gradle-${GRADLE_VERSION}/gradle/wrapper/gradle-wrapper.jar" "$WRAPPER_DIR/gradle-wrapper.jar"
          else
            echo "Error: gradle-wrapper.jar not found in expected locations within the distribution."
            exit 1
          fi
          
          rm -rf gradle-distribution.zip "$TEMP_UNZIP_DIR"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        # This step builds the debug APK.
        run: |
          ./gradlew assembleDebug --stacktrace

      - name: Create GitHub Release
        # This step creates a new GitHub Release using the pushed tag.
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is automatically provided by GitHub Actions
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Debug APK
        # This step uploads the generated debug APK to the newly created GitHub Release.
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk # Path for debug APK
          asset_name: app-debug-${{ github.ref_name }}.apk # Naming the asset with the tag name
          asset_content_type: application/vnd.android.package-archive